# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        MainBundle\Entity\User:          
          #algorithm: plaintext
          algorithm: bcrypt
        
    providers:
        our_db_provider:
            entity:
                class: MainBundle:User
                property: email
            

    firewalls:
       dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

       main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[email]
                password_parameter: login[password]
                always_use_default_target_path: true       
                default_target_path: /panel
                use_referer:         false
                success_handler: login_success_handler
            provider: our_db_provider
            logout:
                path:   /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/panel/answer, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/panel, roles: ROLE_USER }
      