# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#    my_type_form:
#          class: MaibBundle\Form\RegistrationType
#          tags:
#             -  { name: form.type }
        
     login_success_handler:
        class: MainBundle\Handler\AuthenticationHandler
        arguments:  ['@router', '@security.authorization_checker', '@doctrine']
        tags:
            - { name: 'monolog.logger', channel: 'security' }